# Generated by Django 2.2.1 on 2019-07-26 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'technology',
                'verbose_name_plural': 'technologies',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('display', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], max_length=25)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('project_status', models.CharField(choices=[('In Progress', 'In Progress'), ('Complete', 'Complete'), ('Indefinite', 'Indefinite')], max_length=25)),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('github_link', models.URLField()),
                ('tech', models.ManyToManyField(to='portfolio.Technology')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'ordering': ['-start_date', '-created_on'],
            },
        ),
    ]
